services:
 
  web_nginx:
    image: nginx
    hostname: web_nginx
    container_name: web_nginx
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./www_data:/usr/share/nginx/html
      
  web_php:
    build:
      context: ./php/
      args:
        buildno: 2023101101
    hostname: web_php
    container_name: web_php
    restart: unless-stopped
    depends_on:
        - web_db
        - web_nginx
    user: root
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./www_data:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
 
  web_db:
    image: mysql
    hostname: web_db
    container_name: web_db
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      MYSQL_DATABASE: website
      MYSQL_USER: website
      MYSQL_PASSWORD: website123
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./mysql_data:/var/lib/mysql
 
  web_pma:
    image: phpmyadmin
    hostname: web_pma
    container_name: web_pma
    restart: unless-stopped
    depends_on:
        - web_db
        - web_nginx
    environment:
      TZ: "Europe/Moscow"
      PMA_HOST: web_db
      UPLOAD_LIMIT: 50M
    ports:
      - 8080:80
